### ISSUE TITLE
please

### ISSUE THREAD

**Issue by Danilwsk** [GamerMJay/BetterRename#1]
when I write /rename, nothing happens, although the plugin is installed on the server, it doesn 't seem to work

**Comment by GamerMJay** [comment]
Thanks  for you Bug Report

**Comment by Danilwsk** [comment]
and can you please that I could change the description to the description of the command to do

**Comment by Danilwsk** [comment]
I have a lead when you write /rename so I can make a description

**Comment by Danilwsk** [comment]
add description to plugin.yml so that I can change the description

**Comment by GamerMJay** [comment]
Hey, rename works now
