### ISSUE TITLE
Pleas

### ISSUE THREAD

**Issue by Danilwsk** [GamerMJay/BetterRename#2]
You can change, I can only rename the item by 1 word, not by 2 or more.
Please do so that I can rename the subject to more words.

**Comment by GamerMJay** [comment]
Have you "§bTest 123" did?

**Comment by GamerMJay** [comment]
And sorry for my english i use translater 😅

**Comment by GamerMJay** [comment]
Use /rename "test Test" and it works out

**Comment by Danilwsk** [comment]
I also use a translator since I am Russian

**Comment by Danilwsk** [comment]
I enter it this way, but it turns out only 1 word

**Comment by Danilwsk** [comment]
I can shoot a video

**Comment by jvstinxz** [comment]
Are you sure that you use "" ?

**Comment by Danilwsk** [comment]
Yes I definitely use

**Comment by GamerMJay** [comment]
That's how it works for me

**Comment by GamerMJay** [comment]
This is not due to the plugin but to your server apparently or something

**Comment by GamerMJay** [comment]
This is not due to the plugin but to your server apparently or something

**Comment by Danilwsk** [comment]
And then I understood
