### ISSUE TITLE
Plis

### ISSUE THREAD

**Issue by Danilwsk** [GamerMJay/BetterRename#3]
For some reason, sometimes when I want to rename an item, it crashes after entering a command

**Comment by GamerMJay** [comment]
Have you the new update?

**Comment by Danilwsk** [comment]
Yes new update

**Comment by GamerMJay** [comment]
It works for me, is there an error?

**Comment by GamerMJay** [comment]
Show me your config.yml

**Comment by Danilwsk** [comment]
![Uploading Screenshot_20220130_153909_com.alphainventor.filemanager.jpg…]()

**Comment by Danilwsk** [comment]
Only words in "" in another language

**Comment by Danilwsk** [comment]
There is no error in the console , but sometimes crashes when entering

**Comment by GamerMJay** [comment]
I can't see the photo

**Comment by jvstinxz** [comment]
A new version ist now available try this please

**Comment by Danilwsk** [comment]
![Screenshot_20220130_153909_com alphainventor filemanager](https://user-images.githubusercontent.com/98532064/151696371-da000cc2-87d5-40fc-b80a-766f71375350.jpg)

**Comment by Danilwsk** [comment]
In github, he writes this has 1 problem, maybe it crashes because of it?

**Comment by Danilwsk** [comment]
![Screenshot_20220130_154542_com android chrome](https://user-images.githubusercontent.com/98532064/151696459-15593392-38f7-48e2-9f71-ca0436e9c9aa.jpg)

**Comment by Danilwsk** [comment]
![Screenshot_20220130_154540_com android chrome](https://user-images.githubusercontent.com/98532064/151696463-64ed6968-b9d2-4f1e-8f0a-4b7e44c4ac86.jpg)

**Comment by GamerMJay** [comment]
I know

**Comment by Danilwsk** [comment]
It was I who saw that because of someone's commit it was not possible to make an assembly

**Comment by Danilwsk** [comment]
I think it crashes because of this

**Comment by jvstinxz** [comment]
But it works on our server.

**Comment by Danilwsk** [comment]
The update is new , pmmp is also updated , but it seems to work , but why does it crash when entering

**Comment by GamerMJay** [comment]
https://www.mediafire.com/file/2iarhpshhnx352x/BetterRename.phar/file

**Comment by GamerMJay** [comment]
Send the error!

**Comment by Danilwsk** [comment]
yes, but I don't use phar, I download the assembly and unpack it in plugins

**Comment by Danilwsk** [comment]
download this in order to have access to plugin.yml to change the description

**Comment by GamerMJay** [comment]
do Have you DevTools?

**Comment by GamerMJay** [comment]
do you have DevTools*

**Comment by Danilwsk** [comment]
and in config.yml only a description of the execution of commands

**Comment by Danilwsk** [comment]
Yes devtools is available

**Comment by GamerMJay** [comment]
Mhm..

**Comment by Danilwsk** [comment]
If yato. it's not clear, sorry for my translator

**Comment by Danilwsk** [comment]
if anything*

**Comment by jvstinxz** [comment]
Can you send the error please?

**Comment by Danilwsk** [comment]
There is no error in the console, crashes and shows "server closed"

**Comment by GamerMJay** [comment]
https://www.mediafire.com/file/aw0nr4m6bvrcxcn/BetterRename-main.zip/file

**Comment by Danilwsk** [comment]
thank you , it stopped flying out
